apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain2
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
  tags: costcenter=1234, application=test1
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
